{{- if not .Values.deployment.useExternalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  namespace: {{ .Values.deployment.namespace }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.token }}
{{- end }}