apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-updater
  template:
    metadata:
      labels:
        app: dns-updater
    spec:
      containers:
      - name: dns-updater
        image: myapp:latest
      serviceAccountName: dns-updater